nginx:
  image: nginx
  volumes:
  - ./certs:/etc/ssl/certs
  - ./conf.d:/etc/nginx/conf.d
  ports:
  - 80:80
  - 443:443
  links:
  - rancher-server
rancher-server:
  image: rancher/server:stable
  command: --db-host db
  restart: unless-stopped
  volumes:
    - rancher-lib-cattle:/var/lib/cattle
  links:
    - db
db:
  image: mysql
  volumes:
    - rancher-lib-mysql:/var/lib/mysql
    - rancher-log-mysql:/var/log/mysql
  environment:
    MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    MYSQL_DATABASE: cattle
    MYSQL_USER: cattle
    MYSQL_PASSWORD: cattle
